name: Robot Poceada

on:
  schedule:
    # Minuto 15, Hora 0, Días: Domingo(0), Miércoles(3), Viernes(5) (UTC)
    - cron: '15 0 * * 0,3,5'
  workflow_dispatch: 

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Bajar código
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: |
          pip install requests beautifulsoup4 pypdf

      - name: Ejecutar Robot
        run: python scraper.py

      - name: Guardar cambios
        run: |
          git config --global user.name 'Robot Poceada'
          git config --global user.email 'robot@noreply.github.com'
          git add datos_poceada.json
          git commit -m "Nuevos resultados sorteo" || exit 0
          git push