name: Robot Poceada

on:
  schedule:
    # CRON JOB (Horario UTC)
    # Argentina es UTC-3.
    # 21:45 ARG = 00:45 UTC
    # 22:15 ARG = 01:15 UTC
    # 22:45 ARG = 01:45 UTC
    # Días: Domingo(0), Miércoles(3), Viernes(5)
    - cron: '15,45 0,1 * * 0,3,5'
    
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Bajar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install requests beautifulsoup4 pypdf urllib3

      - name: Ejecutar Robot
        run: python scraper.py

      - name: Guardar cambios
        run: |
          git config --global user.name 'Robot Poceada'
          git config --global user.email 'robot@noreply.github.com'
          git add datos_poceada.json ultimo_id_web.txt backups/
          git commit -m "Nuevos resultados sorteo" || echo "Nada nuevo por ahora"
          git push